# Generated by Django 3.1.2 on 2020-10-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(choices=[('шт', 'шт'), ('кг', 'кг')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
